def generate_itinerary_markdown(itinerary: dict) -> str:
    """
    Converts itinerary data into a well-structured Markdown document.
    """

    # --------------------------------------------------
    # Header
    # --------------------------------------------------
    md = f"# 🌍 Travel Itinerary: {itinerary.get('destination', 'My Trip')}\n\n"

    # --------------------------------------------------
    # Trip Overview
    # --------------------------------------------------
    md += "## ✈️ Trip Overview\n"
    md += f"- **Destination:** {itinerary.get('destination', '-')}\n"

    if itinerary.get("start_date") and itinerary.get("end_date"):
        md += f"- **Dates:** {itinerary['start_date']} → {itinerary['end_date']}\n"

    md += "\n"

    # --------------------------------------------------
    # Preferences
    # --------------------------------------------------
    preferences = itinerary.get("preferences", {})
    if preferences:
        md += "## 🎯 Preferences\n"
        for key, value in preferences.items():
            if value:
                label = key.replace("_", " ").title()
                if isinstance(value, list):
                    value = ", ".join(value)
                md += f"- **{label}:** {value}\n"
        md += "\n"

    md += "---\n\n"

    # --------------------------------------------------
    # AI Overview (optional but recommended)
    # --------------------------------------------------
    ai_itinerary = itinerary.get("itinerary_data", {})
    overview = ai_itinerary.get("overview")
    if overview:
        md += "## 🧭 Trip Summary\n"
        md += f"{overview}\n\n"
        md += "---\n\n"

    # --------------------------------------------------
    # Daily Breakdown
    # --------------------------------------------------
    days = ai_itinerary.get("days", [])

    for day in days:
        md += f"## 📅 Day {day.get('day', '')}: {day.get('title', '')}\n\n"

        if day.get("morning"):
            md += f"### 🌅 Morning\n{day['morning']}\n\n"

        if day.get("afternoon"):
            md += f"### 🌞 Afternoon\n{day['afternoon']}\n\n"

        if day.get("evening"):
            md += f"### 🌆 Evening\n{day['evening']}\n\n"

        if day.get("food"):
            md += f"### 🍽️ Food Recommendations\n{day['food']}\n\n"

        if day.get("notes"):
            md += f"### 📝 Notes\n{day['notes']}\n\n"

        md += "---\n\n"

    # --------------------------------------------------
    # Footer
    # --------------------------------------------------
    md += "*Generated by **Nisha Travel AI*** ✨\n"

    return md
