def generate_itinerary_markdown(itinerary: dict) -> str:
    """
    Converts itinerary data into a well-structured Markdown document.
    """
    # Header Section
    md = f"# Travel Itinerary: {itinerary.get('destination', 'My Trip')}\n\n"
    
    # Quick Info
    md += "## Trip Overview\n"
    md += f"- **Destination:** {itinerary.get('destination')}\n"
    if itinerary.get('start_date') and itinerary.get('end_date'):
        md += f"- **Dates:** {itinerary.get('start_date')} to {itinerary.get('end_date')}\n"
    
    # Preferences
    preferences = itinerary.get('preferences', {})
    if preferences:
        md += "\n### Preferences\n"
        for key, value in preferences.items():
            if value:
                md += f"- **{key.replace('_', ' ').capitalize()}:** {value}\n"
    
    md += "\n---\n\n"

    # Daily Schedule
    # Assuming itinerary_data is a list of days or a structured string
    itinerary_content = itinerary.get('itinerary_data', '')
    
    if isinstance(itinerary_content, list):
        for day in itinerary_content:
            md += f"## Day {day.get('day')}: {day.get('theme', '')}\n"
            for activity in day.get('activities', []):
                md += f"- **{activity.get('time', '')}**: {activity.get('description', '')}\n"
            md += "\n"
    else:
        # If it's stored as a large text block, we append it directly
        md += "## Detailed Itinerary\n"
        md += f"{itinerary_content}\n"

    md += "\n\n---\n*Generated by Nisha Travel AI*"
    return md